groups:
  - name: Critical alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
          summary: Instance {{ $labels.instance }} downestart=on-failure



      - alert: PrometheusConfigurationReloadFailure
        expr: prometheus_config_last_reload_successful != 1
        for: 5m
        labels:
          project: "{{$labels.project}}"
          severity: critical
        annotations:
          title: Prometheus configuration reload failure
          description: "Prometheus configuration reload error"

      - alert: PrometheusTooManyRestarts
        expr: changes(process_start_time_seconds{job=~"prometheus|alertmanager"}[15m]) > 2
        for: 5m
        labels:
          project: "{{$labels.project}}"
          severity: critical
        annotations:
          summary: Prometheus too many restarts
          description: "Prometheus has restarted more than twice in the last 15 minutes. It might be crashlooping"

      - alert: PrometheusNotificationsFailed
        expr: sum(increase(alertmanager_notifications_failed_total{integration="webhook"}[5m])) by (integration, job) > 40
        for: 5m
        labels:
          project: "{{$labels.project}}"
          severity: critical
        annotations:
          summary: Prometheus too many failed notifications
          description: "Prometheus too many failed notifications"

  - name: Systemd alerts
    rules:
      - alert: SystemdServiceFailed
        expr: node_systemd_unit_state{state="failed", name!="dnf-makecache.service"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          title: "{{ $labels.name }} failed"
          description: "systemd service {{ $labels.name }} failed"

      - alert: DiskBusy
        expr: rate(node_disk_io_time_seconds_total{device!~"(md|dm).*"}[5m]) * 100 > 90
        for: 1m
        labels:
          severity: warning
        annotations:
          title: '{{ $labels.device }} busy {{ $value | printf "%.0f"}}%'
          description: 'Disk {{ $labels.device }} busy {{ $value |printf "%.0f"}}%'

      - alert: HostOutOfMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes *100 < 10)
        for: 2m
        labels:
          severity: critical
        annotations:
          title: 'Host out of memory ({{ $value | printf "%.0f"}}%)'
          description: 'Node memory is filling up ({{ $value | printf "%.0f"}}%< 10%)'
      - alert: SystemLoad_5m
        expr: (avg by(job,instance) (node_load5) / count by(job,instance)(count by(cpu,job,instance) (node_cpu_seconds_total)) * 100) >= 100
        for: 1m
        labels:
          severity: "{{ if ge $value 105.0 }}critical{{ else }}warning{{ end}}"
        annotations:
          title: 'System Load 5m: {{ $value | printf "%.0f"}}%'
          description: 'System Load 5m too high ({{ $value | printf "%.0f"}}%)for 1 minutes'

  - name: BlackBox alerts
    rules:
      - alert: BlackboxProbeFailed
        expr: probe_success{} != 1
        for: 2m
        labels:
          severity: critical
        annotations:
          title: "Blackbox probe failed. {{$labels.instance }}"
          description: "Blackbox probe failed (instance {{ $labels.instance}})"

      - alert: BlackboxProbeHttpFailure
        expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
          description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxProbeSlowPing
        expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Blackbox probe slow ping (instance {{ $labels.instance }})
          description: "Blackbox ping took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxProbeSlowHttp
        expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Blackbox probe slow HTTP (instance {{ $labels.instance }})
          description: "HTTP request took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - name: Hardware alerts
    rules:
      - alert: DiskSpace50%Free
        expr: node_exporter:node_filesystem_free:fs_used_percents >= 50
        labels:
          severity: moderate
        annotations:
          summary: "Instance {{ $labels.instance }} is half or lower on disk space"
          description: "{{ $labels.instance }} has only {{ $value }}% free."

      - alert: HighCpuLoad
        expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) > 0.8) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostPhysicalComponentTooHot
        expr: ((node_hwmon_temp_celsius * ignoring(label) group_left(instance, job, node, sensor) node_hwmon_sensor_label{label!="tctl"} > 75)) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host physical component too hot (instance {{ $labels.instance }})
          description: "Physical hardware component too hot\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostNetworkBondDegraded
        expr: (node_bonding_active - node_bonding_slaves) != 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host Network Bond Degraded (instance {{ $labels.instance }})
          description: "Bond \"{{ $labels.device }}\" degraded on \"{{ $labels.instance }}\".\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostClockNotSynchronising
        expr: min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host clock not synchronising (instance {{ $labels.instance }})
          description: "Clock not synchronising. Ensure NTP is configured on this host.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOutOfDiskSpace
        expr: ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of disk space (instance {{ $labels.instance }})
          description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOutOfInodes
        expr: (node_filesystem_files_free{fstype!="msdosfs"} / node_filesystem_files{fstype!="msdosfs"} * 100 < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of inodes (instance {{ $labels.instance }})
          description: "Disk is almost running out of available inodes (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostClockSkew
        expr: ((node_timex_offset_seconds > 0.05 and deriv(node_timex_offset_seconds[5m]) >= 0) or (node_timex_offset_seconds < -0.05 and deriv(node_timex_offset_seconds[5m]) <= 0)) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Host clock skew (instance {{ $labels.instance }})
          description: "Clock skew detected. Clock is out of sync. Ensure NTP is configured correctly on this host.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - name: Postgres alerts
    rules:
      - alert: PostgresqlDown
        expr: pg_up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Postgresql down (instance {{ .instance }})
          description: Postgresql instance is downn VALUE = {{ }}n LABELS = {{ }}

      - alert: PostgresqlRestarted
        expr: time() - pg_postmaster_start_time_seconds < 60
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Postgresql restarted (instance {{ .instance }})
          description: Postgresql restartedn VALUE = {{ }}n LABELS = {{ }}

      - alert: PostgresqlExporterError
        expr: pg_exporter_last_scrape_error > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Postgresql exporter error (instance {{ .instance }})
          description: Postgresql exporter is showing errors. A query may be buggy in query.yamln VALUE = {{ }}n LABELS = {{ }}

