route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '7155226222:AAGoBdtE1aguTiXQsJRqEWmuynKwuMpq9Bw'
        api_url: 'https://api.telegram.org'
        chat_id: -1002099863732
        parse_mode: ''
        message: "Alertmanager \n------------------ \n Alertname: {{  .GroupLabels.alertname}}\n Severity:{{ .CommonLabels.severity }}\n Instance: {{ .CommonLabels.instance }}\n Description: {{ .CommonAnnotations.description }}"
