global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'example'
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']
rule_files:
  - "alert-rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'blackboxcheck'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['localhost:9100', 'mail.ru']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']
  - job_name: postgresql
    static_configs:
      - targets: ['localhost:9187']
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:80']
